/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.edicoes;

import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import model.dao.Dao;
import model.dao.NotaDaoImpl;
import model.pojo.Nota;

public class EditarNotaGUI extends javax.swing.JFrame {

    private static Nota nota;
    private static Dao notaDao = NotaDaoImpl.getInstancia();
    private static EntityManager em;
    
    /**
     * Creates new form EditarNotaGUI
     */
    public EditarNotaGUI() {
        initComponents();
        setTitle("EDITAR REGISTRO DE NOTA");
        setVisible(true);
    }
    
    /**
     *
     * @param em gerenciador de entidades para o BD
     */
    public EditarNotaGUI(EntityManager em) {
        this();
        EditarNotaGUI.em = em;
        bloquearEdicao(true);
        bloquearFramesNaoEditaveis();
    }

    /**
    *
    * @param bloquear determina se a edição será ou não permitida
    */
    public void bloquearEdicao (Boolean bloquear) {
        CampoID.setEditable(bloquear);
        CampoNota.setEditable(!bloquear);
        BotaoConcluir.setEnabled(!bloquear);
    }
    
    public void bloquearFramesNaoEditaveis() {
        CampoAluno.setEditable(false);
        CampoAtividade.setEditable(false);
    }
    
    /**
     *
     * @param txtCampo1 atualiza o campo com o valor corrente da variável
     * @param txtCampo2 atualiza o campo com o valor corrente da variável
     * @param txtCampo3 atualiza o campo com o valor corrente da variável
     */
    public void setTexts (String txtCampo1, String txtCampo2, String txtCampo3) {
        CampoNota.setText(txtCampo1);
        CampoAluno.setText(txtCampo2);
        CampoAtividade.setText(txtCampo3);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelNota = new javax.swing.JLabel();
        labelAluno = new javax.swing.JLabel();
        labelAtividade = new javax.swing.JLabel();
        CampoNota = new javax.swing.JTextField();
        CampoAluno = new javax.swing.JTextField();
        CampoAtividade = new javax.swing.JTextField();
        BotaoConcluir = new javax.swing.JButton();
        BotaoFechar = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        CampoID = new javax.swing.JTextField();
        BotaoSuperior = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        labelNota.setText("Nota:");

        labelAluno.setText("Aluno:");

        labelAtividade.setText("Atividade:");

        BotaoConcluir.setText("Concluir");
        BotaoConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConcluirActionPerformed(evt);
            }
        });

        BotaoFechar.setText("Fechar");
        BotaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharActionPerformed(evt);
            }
        });

        labelID.setText("ID:");

        BotaoSuperior.setText("Pesquisar");
        BotaoSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSuperiorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAtividade)
                    .addComponent(labelAluno)
                    .addComponent(labelNota)
                    .addComponent(labelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 167, Short.MAX_VALUE)
                        .addComponent(CampoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CampoAluno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CampoAtividade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CampoID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(BotaoSuperior)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(BotaoConcluir)
                .addGap(18, 18, 18)
                .addComponent(BotaoFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(CampoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSuperior))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNota))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAluno))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAtividade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoConcluir)
                    .addComponent(BotaoFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConcluirActionPerformed
        // TODO add your handling code here:
        nota.setNota(Double.valueOf(CampoNota.getText()));
        try {
            notaDao.atualizar(em, nota);
        } catch (Exception ex) {
            //Logger.getLogger(EditarTurmaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(rootPane, "EDIÇÃO EFETUADA!", "INFORMAÇÃO",
                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotaoConcluirActionPerformed

    private void BotaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_BotaoFecharActionPerformed

    private void BotaoSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSuperiorActionPerformed
        // TODO add your handling code here:
        if (BotaoSuperior.getText().equals("Pesquisar")) {
            Nota nota = (Nota) notaDao.obter(em, CampoID.getText());
            if (nota != null) {
                EditarNotaGUI.nota = nota;
                bloquearEdicao(false);
                BotaoSuperior.setText("Alterar");
                setTexts(nota.getNota().toString(), nota.getAluno().getNome(),
                        nota.getAtividade().getNome());
            }
            else
                JOptionPane.showMessageDialog(rootPane, "REGISTRO DE NOTA NÃO CADASTRADO!", "AVISO", 
                        JOptionPane.WARNING_MESSAGE);
        }
        else if (BotaoSuperior.getText().equals("Alterar")) {
            BotaoSuperior.setText("Pesquisar");
            bloquearEdicao(true);
            setTexts("","","");
        }
    }//GEN-LAST:event_BotaoSuperiorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarNotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarNotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarNotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarNotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarNotaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConcluir;
    private javax.swing.JButton BotaoFechar;
    private javax.swing.JButton BotaoSuperior;
    private javax.swing.JTextField CampoAluno;
    private javax.swing.JTextField CampoAtividade;
    private javax.swing.JTextField CampoID;
    private javax.swing.JTextField CampoNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAluno;
    private javax.swing.JLabel labelAtividade;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNota;
    // End of variables declaration//GEN-END:variables
}
